### PR TITLE
Issue 183b

### PR DESCRIPTION
**Pull request by mattpetrucci**
New intrinsics for the iPad Pro M4. 11 and 13 inch models have the same cameras, so it includes new folders for each model (there are two for each size per this convention https://stackoverflow.com/questions/26028918/how-to-determine-the-current-iphone-device-model).

### CODE REVIEW

**Review by antoinefalisse — APPROVED** [review]
Looking good. Thanks.
Did you have a chance to test w/ a full data collection?

**Comment by mattpetrucci** [comment]
Not yet, but we could!

**Comment by carmichaelong** [comment]
If we want to test, perhaps we point this PR to `dev` and then test there? Or @antoinefalisse was there some other way you prefer to test this type of change?

**Comment by suhlrich** [comment]
Yes we usually go dev, so an end to end test, the dev into main

On Oct 29, 2024, at 10:37 AM, carmichaelong ***@***.***> wrote:

﻿

If we want to test, perhaps we point this PR to dev and then test there? Or @antoinefalisse<https://github.com/antoinefalisse> was there some other way you prefer to test this type of change?

**Pull request merged**
