### PR TITLE
main: update client info

### PR DESCRIPTION
**Pull request by carmichaelong**
Supersedes #198. Points to AWS main image, and added some extra commenting.

### CODE REVIEW

**Comment by carmichaelong** [comment]
Issue opened in #200 for further changes to clean up the docker build workflow

**Review by antoinefalisse — APPROVED** [review]
LGTM

**Comment by AlbertoCasasOrtiz** [comment]
If this is good feel free to merge! It should automatically update the AWS machine, right?

**Comment by antoinefalisse** [comment]
No, you still need to re-launch (`make run` only if on main branch and pulling images from ECR; `make` and then `make run` if building images locally).

**Pull request merged**
